#define DEVSTAGE_BETA    0
#define DEVSTAGE_RELEASE 1

// comment this out for release builds
#define VERSION_PRERELEASE

#define VERSION_STAGE DEVSTAGE_RELEASE
#define VERSION_MAJOR 2
#define VERSION_MINOR 0
#define VERSION_PATCH 0

#define _STR(x) #x
#define STR(x) _STR(x)

#define SATURN_VERSION_MAJOR STR(VERSION_STAGE)   "." STR(VERSION_MAJOR)
#define SATURN_VERSION_MINOR SATURN_VERSION_MAJOR "." STR(VERSION_MINOR)
#define SATURN_VERSION_PATCH SATURN_VERSION_MINOR "." STR(VERSION_PATCH)

#if VERSION_MINOR == 0 && VERSION_PATCH == 0
#define SATURN_VERSION SATURN_VERSION_MAJOR
#elif VERSION_PATCH == 0
#define SATURN_VERSION SATURN_VERSION_MINOR
#else
#define SATURN_VERSION SATURN_VERSION_PATCH
#endif
